#!/bin/sh

APPDIR=$(dirname "$0")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/final_6Pol.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/itext.jar:$APPDIR/lib/pdf.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar" final_6Pol "$@"
